### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Tacodiva** [Tacodiva/wasm-spider#1]
Specs: [https://webassembly.github.io/JS-BigInt-integration/core/](https://webassembly.github.io/JS-BigInt-integration/core/)

- [X] structured instructions
- [x] import section (importing function + `call` instruction) 
- [x] a more idiomatic way to refer to local variables
- [x] globals (section, import, export and instructions)
- [x] memory (section, import, export and instructions)
- [x] start section
- [x] tables (tables section, import, export, elements section and `call_indirect` instruction)
- [x] `br_table` instruction
- [x] data section
- [x] custom sections
- [x] **Milestone! WASM 1.0 Fully Implemented :tada:**
- [x] type merging
- [x] implement proposal: bulk memory operations
- [x] implement proposal: reference types
- [x] implement proposal: non-trapping float-to-int conversions
- [x] implement proposal: sign-extension operations
- [x] implement proposal: fixed-width SIMD
- [x] Read wasm module in.
- [x] Hella unit tests
- [x] Documentation
- [x] NPM package
